# Generated by Django 3.0.3 on 2020-02-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0002_auto_20200212_2331'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='language',
            table='language',
        ),
        migrations.AlterModelTable(
            name='typology',
            table='typology',
        ),
    ]
