# Generated by Django 3.0.3 on 2020-02-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0003_auto_20200212_2343'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='excursion',
            table='excursion',
        ),
    ]
