# Generated by Django 3.0.3 on 2020-02-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursion', '0004_auto_20200212_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='minimumAge',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='typology',
            name='number',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
